export const services: IService[] = [
  {
    id: 1,
    title: 'Analyse des données & Études de marché',
    slug: 'analyse-donnees',
    description: 'Transformez vos données en décisions stratégiques grâce à des analyses précises et des tableaux de bord interactifs.',
    subServices: [
      'Dashboards Power BI',
      'Reporting KPI',
      'Google Analytics 4 (GA4)',
      'Études de marché',
      'Analyse de la concurrence',
    ],
    image: '/icons/content-strategy.png',
  },
  {
    id: 2,
    title: 'Création de sites Web & Design',
    slug: 'dev',
    description: 'Concevez une présence digitale professionnelle qui inspire confiance et génère des résultats.',
    subServices: [
      'Sites vitrines & e-commerce',
      'Landing pages',
      'UX/UI Design & Figma',
      'Développement Next.js',
      'Responsive Design & maintenance',
    ],
    image: '/icons/mobile-app.png',
  },
  {
    id: 3,
    title: 'Gestion des réseaux sociaux & Contenu',
    slug: 'social-media',
    description: 'Développez votre visibilité et engagez votre audience avec un contenu impactant.',
    subServices: [
      'Community Management',
      'Création de visuels & vidéos (Reels/TikTok)',
      'Calendrier éditorial',
      'Gestion Facebook, Instagram & LinkedIn',
      'Stratégie de contenu',
    ],
    image: '/icons/conversation.png',
  },
  {
    id: 4,
    title: "Stratégie d'acquisition (SEO, GEO & SEA)",
    slug: 'acquisition',
    description: 'Attirez plus de prospects qualifiés grâce à des stratégies de visibilité performantes.',
    subServices: [
      'Audit SEO & SEO Local',
      'Optimisation pour IA (ChatGPT, Gemini, Perplexity)',
      'Google Ads & Meta Ads',
      'Campagnes de génération de leads',
      'Remarketing & optimisation ROI',
    ],
    image: '/icons/shopping.png',
  },
  {
    id: 5,
    title: 'Branding & Identité Visuelle',
    slug: 'branding',
    description: 'Construisez une image de marque forte et mémorable.',
    subServices: [
      'Création de logo',
      'Charte graphique',
      'Cartes de visite',
      'Supports marketing',
    ],
    image: '/icons/pantone.png',
  },
  {
    id: 6,
    title: 'Automatisation & Intelligence Artificielle',
    slug: 'ai',
    description: "Gagnez du temps et automatisez vos processus grâce à l'intelligence artificielle.",
    subServices: [
      'Chatbots IA',
      'Automatisation WhatsApp & Email',
      'CRM & workflows',
    ],
    image: '/icons/ai.png',
  },
]